[meta]
name        = "Listed Records"
author      = "sanket143"
category    = "Leaderboard"
version     = "1.0.0"

[script]
imports = [ "Icons.as", "Formatting.as", "Time.as" ]
dependencies = [ "NadeoServices" ]